Internal improvement: Org scoping
ConsenSys-archive/truffle pull request #2345
Opened 2019-08-29 13:18 UTC by eggplantzzz

Continue org-scoping the packages
  1. truffle-hdwallet-provider --> @truffle/hdwallet-provider
  2. truffle-provider --> @truffle/provider
  3. truffle-provisioner --> @truffle/provisioner
  4. truffle-external-compile --> @truffle/external-compile

2019-08-29 13:33 UTC, eggplantzzz commented
Do we want to consider renaming @truffle/compile to @truffle/compile-solidity now that we are renaming packages?

2019-08-29 16:59 UTC, gnidan approved these changes
I'm into renaming to `@truffle/compile-solidity`!

2019-08-29 23:29 UTC, CruzMolina requested changes
Almost there!

2019-08-29 23:29 UTC, CruzMolina commented on packages/external-compile/package.json
>    },
needs one of these

```
"publishConfig": {
    "access": "public"
  },
```

2019-08-29 23:29 UTC, CruzMolina commented on packages/hdwallet-provider/package.json
>    },
also needs

```
"publishConfig": {
    "access": "public"
  },
```

2019-08-30 15:30 UTC, CruzMolina approved these changes

2019-08-30 15:45 UTC, merged

2023-12-31 02:31 UTC, fFurkanllci reviewed
Yfl